baseURL = 'https://example.org/'
languageCode = 'en-uk'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[[menus.main]]
name= 'Study'
pageRef = '/study'
weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
